version: 0.2

phases:
  install:
    runtime-versions:
      java: 11
    commands:
      - echo "Installing dependencies"
      - mvn install -DskipTests
  pre_build:
    commands:
      - echo "Running pre-build steps"
      - mvn clean
  build:
    commands:
      - echo "Building the application"
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Running post-build steps"
      - echo "Build completed successfully"
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
cache:
  paths:
    - ~/.m2/**/*
